/**
 * Created by polik on 20.07.16.
 */
var zodiacs = [
    {   name: 'Aries',
        ruName: 'Овен',
        position: 0,
        period: ''},
    {   name: 'Taurus',
        ruName: '',
        position: 1,
        period: ''},
    {   name: 'Gemini',
        ruName: '',
        position: 2,
        period: ''},
    {   name: 'Cancer',
        ruName: '',
        position: 3,
        period: ''},
    {   name: 'Leo',
        ruName: '',
        position: 4,
        period: ''},
    {   name: 'Virgo',
        ruName: '',
        position: 5,
        period: ''},
    {   name: 'Libra',
        ruName: '',
        position: 6,
        period: ''},
    {   name: 'Scorpio',
        ruName: '',
        position: 7,
        period: ''},
    {   name: 'Sagittarius',
        ruName: '',
        position: 8,
        period: ''},
    {   name: 'Capricorn',
        ruName: '',
        position: 9,
        period: ''},
    {   name: 'Aquarius',
        ruName: '',
        position: 10,
        period: ''},
    {   name: 'Pasces',
        ruName: '',
        position: 11,
        period: ''},
]